name: TeleportationBow
version: '${project.version}'
main: net.daechler.teleportationbow.TeleportationBow
api-version: 1.19
authors: [Daechler]
description: Wherever the arrow lands, you will be teleported to.
